jobs:
  issue-labeled:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: '${{ github.event.label.name == ''Resolution: Cannot Replicate''}}'
      name: Cannot Replicate
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-comment
        body: 'We''re unable to replicate your issue, if you are able to create a  [PrimeFaces
          Test Reproducer](https://github.com/primefaces/primefaces-test) or add details
          please edit this issue. This issue will be closed if no activities in 20
          days.

          '
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: '${{ github.event.label.name == ''Status: Needs Reproducer''}}'
      name: Needs Reproducer
      uses: actions-cool/issues-helper@v3
      with:
        actions: create-comment
        body: 'Please provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test)
          project. This issue will be closed if no activities in 20 days.

          '
        issue-number: ${{ github.event.issue.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
name: Issue Labeled
on:
  repository_dispatch:
    types: trigger-ga___issues-labeled.yml
permissions:
  contents: read
