jobs:
  issue-close-require:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cannot Replicate
      uses: actions-cool/issues-helper@v3
      with:
        actions: close-issues
        inactive-day: 20
        labels: 'Resolution: Cannot Replicate'
    - continue-on-error: true
      name: Needs Reproducer
      uses: actions-cool/issues-helper@v3
      with:
        actions: close-issues
        inactive-day: 20
        labels: 'Status: Needs Reproducer'
name: Issue Inactive Checker
on:
  repository_dispatch:
    types: trigger-ga___issue-inactive-checker.yml
permissions:
  contents: read
